# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='approved',
            field=models.ManyToManyField(blank=True, related_name='approved_collaborators', to='pm_app.UserProfile'),
        ),
    ]
