# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 11:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pm_app', '0002_team_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('state', models.CharField(choices=[('new', 'new'), ('open', 'open'), ('in progress', 'in progress'), ('done', 'done')], default='new', max_length=11)),
                ('type', models.CharField(choices=[('bug fix', 'bug fix'), ('code', 'code'), ('test', 'test')], max_length=7)),
                ('assigned', models.ManyToManyField(blank=True, related_name='assigned_collaborators', to='pm_app.UserProfile')),
                ('project_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_manager', to='pm_app.UserProfile')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
    ]
